# Gradle
org.gradle.jvmargs=-Xmx2G -XX\:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
java_version=21
# Mod
mod_id=xattack
mod_name=Xattack
mod_license=All rights reserved
mod_version=1.0.0
mod_group_id=io.github.xrbbm
mod_authors=xrbbm, ForgeStove
mod_display_url=https://github.com/ForgeStove/Xattack
mod_issue_url=https://github.com/ForgeStove/Xattack/issues
mod_description=Auto attack mod.
# Version
minecraft_version=1.21.1
loader_version=21.1.176
parchment_version=2024.11.17
# Loader
loader=neoforge
upper_loader=NeoForge
